
const Food = [
    {
      id: 1,
      title: "Classic Caesar Salad",
      image: "salad1.png",
      desc: "Crisp romaine lettuce tossed with creamy Caesar dressing, parmesan cheese, and crunchy croutons.",
      price: "120",
      cat: "Salad",
    },
    {
      id: 2,
      title: "Greek Salad",
      image: "salad1.png",
      desc: "A refreshing mix of tomatoes, cucumbers, onions, olives, and feta cheese, dressed with olive oil and oregano.",
      price: "150",
      cat: "Salad",
    },
    {
      id: 3,
      title: "Chicken Salad Roll",
      image: "salad1.png",
      desc: "Tender chicken salad wrapped in a soft roll with lettuce and your favorite toppings.",
      price: "180",
      cat: "Rolls",
    },
    {
      id: 4,
      title: "Vegetable Spring Rolls",
      image: "salad1.png",
      desc: "Crispy spring rolls filled with fresh vegetables and served with a sweet chili dipping sauce.",
      price: "160",
      cat: "Rolls",
    },
    {
      id: 5,
      title: "Chocolate Lava Cake",
      image: "salad1.png",
      desc: "Warm chocolate cake with a molten chocolate center, perfect for dessert lovers.",
      price: "220",
      cat: "Desserts",
    },
    {
      id: 6,
      title: "Tiramisu",
      image: "salad1.png",
      desc: "Classic Italian dessert made with ladyfingers, espresso, mascarpone cheese, and cocoa.",
      price: "250",
      cat: "Desserts",
    },
    {
      id: 7,
      title: "Club Sandwich",
      image: "salad1.png",
      desc: "A classic sandwich with layers of turkey, bacon, lettuce, and tomato on toasted bread.",
      price: "190",
      cat: "Sandwich",
    },
    {
      id: 8,
      title: "Grilled Cheese Sandwich",
      image: "salad1.png",
      desc: "Simple and comforting, melted cheese between two slices of toasted bread.",
      price: "140",
      cat: "Sandwich",
    },
    {
      id: 9,
      title: "Chocolate Cake",
      image: "salad1.png",
      desc: "Rich and decadent chocolate cake, perfect for any celebration.",
      price: "280",
      cat: "Cake",
    },
    {
      id: 10,
      title: "Red Velvet Cake",
      image: "salad1.png",
      desc: "Moist red velvet cake with cream cheese frosting, a classic favorite.",
      price: "300",
      cat: "Cake",
    },
    {
      id: 11,
      title: "Aloo Paratha",
      image: "salad1.png",
      desc: "Indian flatbread stuffed with spiced mashed potatoes, served with yogurt or pickle.",
      price: "130",
      cat: "Paratha",
    },
    {
      id: 12,
      title: "Paneer Paratha",
      image: "salad1.png",
      desc: "Indian flatbread stuffed with spiced paneer, a flavorful and satisfying meal.",
      price: "170",
      cat: "Paratha",
    },
    {
      id: 13,
      title: "Vegetable Noodles",
      image: "salad1.png",
      desc: "Stir-fried noodles with a mix of colorful vegetables and savory sauces.",
      price: "160",
      cat: "Noodles",
    },
    {
      id: 14,
      title: "Chicken Chow Mein",
      image: "salad1.png",
      desc: "Noodles stir-fried with chicken, vegetables, and a flavorful soy-based sauce.",
      price: "200",
      cat: "Noodles",
    },
    {
      id: 15,
      title: "Spinach Salad",
      image: "salad1.png",
      desc: "Fresh spinach leaves with your choice of toppings and a light vinaigrette dressing.",
      price: "135",
      cat: "Salad",
    },
    {
      id: 16,
      title: "Egg Rolls",
      image: "salad1.png",
      desc: "Crispy rolls filled with pork, vegetables, and spices, served with a dipping sauce.",
      price: "175",
      cat: "Rolls",
    },
    {
      id: 17,
      title: "Cheesecake",
      image: "salad1.png",
      desc: "Creamy cheesecake with a graham cracker crust, a classic dessert.",
      price: "260",
      cat: "Desserts",
    },
    {
      id: 18,
      title: "Brownie",
      image: "salad1.png",
      desc: "Rich and fudgy chocolate brownies, perfect for a sweet treat.",
      price: "155",
      cat: "Desserts",
    },
    {
      id: 19,
      title: "Tuna Sandwich",
      image: "salad1.png",
      desc: "Tuna salad with mayonnaise, celery, and onions on your choice of bread.",
      price: "175",
      cat: "Sandwich",
    },
    {
      id: 20,
      title: "BLT Sandwich",
      image: "salad1.png",
      desc: "Bacon, lettuce, and tomato on toasted bread, a classic and delicious sandwich.",
      price: "185",
      cat: "Sandwich",
    },
    {
      id: 21,
      title: "Carrot Cake",
      image: "salad1.png",
      desc: "Moist carrot cake with cream cheese frosting, a spiced and sweet treat.",
      price: "290",
      cat: "Cake",
    },
    {
      id: 22,
      title: "Banana Cake",
      image: "salad1.png",
      desc: "Sweet and moist banana cake with a creamy frosting, a simple and tasty cake.",
      price: "270",
      cat: "Cake",
    },
    {
      id: 23,
      title: "Mooli Paratha",
      image: "salad1.png",
      desc: "Indian flatbread filled with spiced radish, flavorful and healthy.",
      price: "145",
      cat: "Paratha",
    },
    {
      id: 24,
      title: "Onion Paratha",
      image: "salad1.png",
      desc: "Indian Flatbread stuffed with spiced onion, a tasty and savory dish.",
      price: "155",
      cat: "Paratha",
    },
    {
      id: 25,
      title: "Schezwan Noodles",
      image: "salad1.png",
      desc: "Spicy noodles with vegetables and Schezwan sauce, a flavorful and fiery dish.",
      price: "190",
      cat: "Noodles",
    },
  ];

export const Category=[
    {
        id:"0",
        title : "View All",
        image: "salad.png",
    },
    {
        id:"1",
        title : "Salad",
        image: "salad.png",
    },
    {
        id:"2",
        title : "Rolls",
        image: "salad.png",
    },
    {
        id:"3",
        title : "Desserts",
        image: "salad.png",
    },
    {
        id:"4",
        title : "Sandwich",
        image: 'salad.png',
    },
    {
        id:"5",
        title : "Cake",
        image: 'salad.png',
    },
    {
        id:"6",
        title : "Paratha",
        image: 'salad.png',
    },
    {
        id:"7",
        title : "Noodles",
        image: 'salad.png',
    },
] 

export default Food;