
const Food=[
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },
    {
        id:1,
        title : "Salad",
        image: "salad.png",
        desc: 'lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        price: '100',
        cat: 'salad',
    },

] 

export const Category=[
    {
        id:"1",
        title : "salad",
        image: "salad1.png",
    },
    {
        id:"2",
        title : "Rolls",
        image: "salad1.png",
    },
    {
        id:"3",
        title : "Desserts",
        image: "salad1.png",
    },
    {
        id:"4",
        title : "Sandwich",
        image: 'salad1.png',
    },
    {
        id:"5",
        title : "Cake",
        image: 'salad1.png',
    },
    {
        id:"6",
        title : "Paratha",
        image: 'salad1.png',
    },
    {
        id:"7",
        title : "Noodles",
        image: 'salad1.png',
    },
] 

export default Food;