const sampleData = [
    {
      id: "1",
      title: "Greek salad",
      image: "food_1.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 12,
      cat: "Salad",
    },
    {
      id: "2",
      title: "Veg salad",
      image: "food_2.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 18,
      cat: "Salad",
    },
    {
      id: "3",
      title: "Clover Salad",
      image: "food_3.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 16,
      cat: "Salad",
    },
    {
      id: "4",
      title: "Chicken Salad",
      image: "food_4.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 24,
      cat: "Salad",
    },
    {
      id: "5",
      title: "Lasagna Rolls",
      image: "food_5.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 14,
      cat: "Rolls",
    },
    {
      id: "6",
      title: "Peri Peri Rolls",
      image: "food_6.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 12,
      cat: "Rolls",
    },
    {
      id: "7",
      title: "Chicken Rolls",
      image: "food_7.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 20,
      cat: "Rolls",
    },
    {
      id: "8",
      title: "Veg Rolls",
      image: "food_8.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 15,
      cat: "Rolls",
    },
    {
      id: "9",
      title: "Ripple Ice Cream",
      image: "food_9.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 14,
      cat: "Deserts",
    },
    {
      id: "10",
      title: "Fruit Ice Cream",
      image: "food_10.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 22,
      cat: "Deserts",
    },
    {
      id: "11",
      title: "Jar Ice Cream",
      image: "food_11.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 10,
      cat: "Deserts",
    },
    {
      id: "12",
      title: "Vanilla Ice Cream",
      image: "food_12.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 12,
      cat: "Deserts",
    },
    {
      id: "13",
      title: "Chicken Sandwich",
      image: "food_13.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 12,
      cat: "Sandwich",
    },
    {
      id: "14",
      title: "Vegan Sandwich",
      image: "food_14.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 18,
      cat: "Sandwich",
    },
    {
      id: "15",
      title: "Grilled Sandwich",
      image: "food_15.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 16,
      cat: "Sandwich",
    },
    {
      id: "16",
      title: "Bread Sandwich",
      image: "food_16.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 24,
      cat: "Sandwich",
    },
    {
      id: "17",
      title: "Cup Cake",
      image: "food_17.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 14,
      cat: "Cake",
    },
    {
      id: "18",
      title: "Vegan Cake",
      image: "food_18.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 12,
      cat: "Cake",
    },
    {
      id: "19",
      title: "Butterscotch Cake",
      image: "food_19.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 20,
      cat: "Cake",
    },
    {
      id: "20",
      title: "Sliced Cake",
      image: "food_20.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 15,
      cat: "Cake",
    },
    {
      id: "21",
      title: "Garlic Mushroom ",
      image: "food_21.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 14,
      cat: "Pure Veg",
    },
    {
      id: "22",
      title: "Fried Cauliflower",
      image: "food_22.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 22,
      cat: "Pure Veg",
    },
    {
      id: "23",
      title: "Mix Veg Pulao",
      image: "food_23.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 10,
      cat: "Pure Veg",
    },
    {
      id: "24",
      title: "Rice Zucchini",
      image: "food_24.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 12,
      cat: "Pure Veg",
    },
    {
      id: "25",
      title: "Cheese Pasta",
      image: "food_25.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 12,
      cat: "Pasta",
    },
    {
      id: "26",
      title: "Tomato Pasta",
      image: "food_26.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 18,
      cat: "Pasta",
    },
    {
      id: "27",
      title: "Creamy Pasta",
      image: "food_27.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 16,
      cat: "Pasta",
    },
    {
      id: "28",
      title: "Chicken Pasta",
      image: "food_28.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 24,
      cat: "Pasta",
    },
    {
      id: "29",
      title: "Buttter Noodles",
      image: "food_29.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 14,
      cat: "Noodles",
    },
    {
      id: "30",
      title: "Veg Noodles",
      image: "food_30.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 12,
      cat: "Noodles",
    },
    {
      id: "31",
      title: "Somen Noodles",
      image: "food_31.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 20,
      cat: "Noodles",
    },
    {
      id: "32",
      title: "Cooked Noodles",
      image: "food_32.png",
      desc: "Food provides essential nutrients for overall health and well-being",
      price: 15,
      cat: "Noodles",
    },
  ];
  
  export default sampleData;